### ISSUE TITLE
Fix username/password authentication

### ISSUE THREAD

**Issue by derekfinlinson** [derekfinlinson/node-webresource#1]

**Comment by AdaskoTheBeAsT** [comment]
Hi,

nice work with generator - maybe this will help dyn365-deploy-cli ? (https://medium.com/@and.nil/using-typescript-in-dynamics-365-499a0e56b143)

**Comment by derekfinlinson** [comment]
Looks interesting. I actually fixed this last week. I didn't realize that registering your app with Azure as a web app/api only allows client id/secret authentication. I switched the app to a native app to allow for username/password authentication.
