### ISSUE TITLE
Auth without Azure AD app

### ISSUE THREAD

**Issue by aslanovsergey** [derekfinlinson/node-webresource#26]
Is this possible? Docs says 'either or' but in my case I only want to use my creds without creating special Azure AD App. I tried and it errors about app permissions and wants app.

**Comment by derekfinlinson** [comment]
Yes it works with just username and password without registering an app in Azure AD. Did you go [here](https://login.microsoftonline.com/common/oauth2/authorize?%20response_type=code&client_id=c67c746f-9745-46eb-83bb-5742263736b7&redirect_uri=https://github.com/derekfinlinson/node-webresource) and authorize the app?

**Comment by aslanovsergey** [comment]
I see, thanks
