### ISSUE TITLE
Web resource isn't configured 

### ISSUE THREAD

**Issue by aslanovsergey** [derekfinlinson/node-webresource#29]
Hello Derek,

Please say what could be wrong with my config, none of the resources are published and terminal says:

> Uploading web resources...
Web resource ./dist/authCallback.js is not configured
Web resource ./dist/bundle.js is not configured
Web resource ./dist/authCallback.js.map is not configured
Web resource ./dist/bundle.js.map is not configured
Web resource ./dist/index.html is not configured
Web resource ./dist/authCallback.html is not configured
Publishing web resources...
Uploaded and published web resources

Here is my publishing config 

> {
    "webResources": [
        {
            "name": "new_/orders/authCallback.html",
            "path": "authCallback.html"
        },
        {
            "name": "new_/orders/authCallback.js",
            "path": "authCallback.js"
        },
        {
            "name": "new_/orders/authCallback.js.map",
            "path": "authCallback.js.map"
        },
        {
            "name": "new_/orders/bundle.js",
            "path": "bundle.js"
        },
        {
            "name": "new_/orders/bundle.js.map",
            "path": "bundle.js.map"
        },
        {
            "name": "new_/orders/index.html",
            "path": "index.html"
        }
    ],
    "entries": {}
}

**Comment by derekfinlinson** [comment]
The web resource path needs to be the full path. So it's expecting authCallback.html to be ./dist/authCallback.html.

**Comment by aslanovsergey** [comment]
It helped, thanks
