### ISSUE TITLE
Usage for Crm On-Premise

### ISSUE THREAD

**Issue by haseeb20** [derekfinlinson/node-webresource#6]
Hello derekfinlinson,
is it possible to use this tool to publish files on On-Premise Solutions?

regards,
Haseeb

**Comment by derekfinlinson** [comment]
It's online only since it depends on adal-node. For on prem it would just need some way of authenticating and I'm unsure how to do that.

**Comment by AdaskoTheBeAsT** [comment]
I keep my fingers crossed maybe that would help [https://github.com/gongfuPanada/node-dynamicscrm-api](https://github.com/gongfuPanada/node-dynamicscrm-api)
